# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/dockers


name: Docker-CI

trigger:
- master

resources:
- repo: self

variables:
  tagImageDocker: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tagImageDocker)
      

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: acr   #service conntection 
    - task: Docker@2
      displayName: BuildandPush
      inputs:
        command: buildAndPush
        repository: 'buildimages' #commm
        tags: |
          $(tagImageDocker)
